### ISSUE TITLE
Auto fill pswrd

### ISSUE THREAD

**Issue by sanderDijkxhoorn** [PrashantRaj18198/proton-vpn-account-generator#1]
Hey! I can't seem to get the pass part working I made my own version using the ProtonMail source just like u but filling in the password part is not working for some reason it can't interact with it.

**Comment by PrashantRaj18198** [comment]
It's probably because you aren't waiting for the DOM to mutate. You need to wait for the element you are rendering to capture it, after that you can just inject the keys.

**Comment by sanderDijkxhoorn** [comment]
> It's probably because you aren't waiting for the DOM to mutate. You need to wait for the element you are rendering to capture it, after that you can just inject the keys.

Thanks for the reply even tho it is very late :)
